
spring.datasource.url=jdbc:mysql://localhost:3306/peluqueria_db
spring.datasource.username=root
spring.datasource.password=root

# Para que Java cree o actualice las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

# Para ver en la consola lo que Java le pide a MySQL
spring.jpa.show-sql=true